site_name: 供应链项目Java服务文档
theme:
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  favicon: 'assets/images/favicon.png'
  logo:
    icon: 'cloud'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  language: 'zh'
  name: material
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

extra:
  search:
    language: 'en, zh'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
